version: "3.4"
services:

  jenkins:
    build: ./jenkins
    ports:
      - "8081:8080"
    environment:
      - MAPI_TOKEN
      - JENKINS_ADMIN_PASSWORD
      - MAYHEM_TOKEN
      - MAYHEM_URL
      - MAYHEM_USERNAME

  gitlab:
    image: '${GITLAB_IMAGE_OVERRIDE:-gitlab/gitlab-ce}'
    restart: always
    hostname: 'gitlab'
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
      # Set the runner registration token to equal the root password
      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: ${GITLAB_ROOT_PASSWORD}
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
    ports:
      - "8080:80"
      - "8043:443"
      - "8022:22"
    volumes:
      # inserts PAT token (from .env GITLAB_ROOT_PASSWORD)
      - ./gitlab/25_api_personal_access_token.rb:/opt/gitlab/embedded/service/gitlab-rails/db/fixtures/production/25_api_personal_access_token.rb
    
      # Currently not persisting volumes because this is a throwaway container
      #   - ./gitlab-config:/etc/gitlab
      #   - ./gitlab-logs:/var/log/gitlab
      #   - ./gitlab-data:/var/opt/gitlab

  # this registers the runner and writes to the config.toml, which is used by gitlab-runner
  gitlab-runner-register:
    image: gitlab/gitlab-runner
    # todo: probably we want a docker type executor, not shell
    command: 'register --executor shell --registration-token ${GITLAB_ROOT_PASSWORD} --url http://gitlab -n'
    restart: "no"
    depends_on:
      gitlab:
        condition: service_healthy
    links:
      - gitlab:gitlab
    volumes:
      - ./gitlab-runner/config.toml:/etc/gitlab-runner/config.toml

  # this clones, pushes and keeps mirroring our example repos to Gitlab. 
  # if you make changes to the shell script run with --force-recreate
  mayhem-action-example-pusher:
    image: alpine
    entrypoint: sh
    command: /mayhem-action-example-pusher.sh
    restart: "no"
    depends_on:
      gitlab:
        condition: service_healthy
    volumes:
      - ./mayhem-action-example-pusher.sh:/mayhem-action-example-pusher.sh
    environment:
      - GITLAB_ROOT_PASSWORD

  # this is the actual runner that depends on being bootstrapped by gitlab-runner-register
  gitlab-runner:
    build: ./gitlab-runner
    depends_on:
      # needs to be registered first before it can start running
      - gitlab-runner-register
    volumes:
      - ./gitlab-runner/config.toml:/etc/gitlab-runner/config.toml
      - /var/run/docker.sock:/var/run/docker.sock

  # Gitlabs Configuration as Code (CasC).
  # Kind of overkill to use since we only create instance variables currently
  gitlab-casc:
    image: hoffmannlaroche/gcasc
    restart: "no"
    depends_on:
      gitlab:
        condition: service_healthy
    links:
      - gitlab:gitlab
    volumes:
      - ./gcacs:/workspace
    environment:
      - GITLAB_CLIENT_CONFIG_FILE=/workspace/client.cfg
      - GITLAB_CONFIG_FILE=/workspace/config.yml
      - GITLAB_CLIENT_TOKEN=${GITLAB_ROOT_PASSWORD}
      - MAPI_TOKEN=${MAPI_TOKEN}
      - MAYHEM_TOKEN=${MAYHEM_TOKEN}
      - MAYHEM_URL=${MAYHEM_URL}
      - MAYHEM_USERNAME=${MAYHEM_USERNAME}

