version: "3.4"
services:
  gitlab-casc:
    image: hoffmannlaroche/gcasc
    container_name: gitlab-casc
    depends_on:
      - gitlab
    links:
      - gitlab:gitlab
    volumes:
      - ./gcacs:/workspace
    environment:
      - GITLAB_CLIENT_CONFIG_FILE=/workspace/client.cfg 
      - GITLAB_CONFIG_FILE=/workspace/config.yml 

  gitlab:
    image: 'yrzr/gitlab-ce-arm64v8'
    restart: always
    hostname: 'gitlab.local'
    container_name: gitlab-ce
    privileged: true
    depends_on:
      - postgresql
    links:
      - postgresql:postgresql
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'qq6UGBwB1orpinslu3e9Tr7M0CawTv2a7U8BJbA6eNg='

        postgresql['enable'] = false
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "gitlab"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        external_url 'http://gitlab.local'
    ports:
      - "8080:80"
      - "8043:443"
      - "8022:22"
    volumes:
      # inserts PAT token ypCa3Dzb23o5nvsixwPA
      - ./gitlab/25_api_personal_access_token.rb:/opt/gitlab/embedded/service/gitlab-rails/db/fixtures/production/25_api_personal_access_token.rb
    #   - ./gitlab-config:/etc/gitlab
    #   - ./gitlab-logs:/var/log/gitlab
    #   - ./gitlab-data:/var/opt/gitlab

  postgresql:
    restart: always
    image: postgres:13.6-alpine
    container_name: gitlab-postgres
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab
      - POSTGRES_DB=gitlabhq_production
      - TZ=America/Bogota
      - PGDATA=/data
    # volumes:
    #   - ./gitlab-db-data:/data
    ports:
      - "5432:5432"