concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "4bee8718e433"
  url = "http://gitlab"
  id = 1
  token = "CBQ7Hj5oWC3MdLWG6JCN"
  token_obtained_at = 2023-05-16T19:09:01Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "9cadf0c7c3e2"
  url = "http://gitlab"
  id = 1
  token = "rsABUYsCUAGfxaprpmyu"
  token_obtained_at = 2023-05-16T19:24:49Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "116c669bf6d3"
  url = "http://gitlab"
  id = 1
  token = "UR_EqmcfhtMVwNk9WTxa"
  token_obtained_at = 2023-05-16T19:38:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "f05b33e17708"
  url = "http://gitlab"
  id = 1
  token = "aW3AV7pf9Xq3RzZhp83g"
  token_obtained_at = 2023-05-16T19:53:02Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "a7e3653de0de"
  url = "http://gitlab"
  id = 1
  token = "6io4Mk8xKRcPynRfPThL"
  token_obtained_at = 2023-05-16T20:28:29Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "15df62aa8a38"
  url = "http://gitlab"
  id = 1
  token = "tKDrhYB-ckYZ-Jxhhsk9"
  token_obtained_at = 2023-05-16T20:38:52Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "12c23da65c33"
  url = "http://gitlab"
  id = 1
  token = "fnLdqy-x5oQ4dqrx_9By"
  token_obtained_at = 2023-05-16T20:59:46Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "72accfd657db"
  url = "http://gitlab"
  id = 1
  token = "V1o5f5pbmw9z_PoaWy7o"
  token_obtained_at = 2023-05-18T00:10:08Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "cf3ae52f8f2f"
  url = "http://gitlab"
  id = 1
  token = "xm4Prsayq5RMzktRqnTz"
  token_obtained_at = 2023-05-18T00:50:18Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "69f5de6cffa2"
  url = "http://gitlab"
  id = 1
  token = "y_NNRLxuwvBnYfsWtCLk"
  token_obtained_at = 2023-05-18T01:47:49Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "fbcd5350e749"
  url = "http://gitlab"
  id = 1
  token = "3nyYs59G1HxzV3qkWiA3"
  token_obtained_at = 2023-05-18T02:16:12Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "0eab8f7555d0"
  url = "http://gitlab"
  id = 1
  token = "e9USzLxJkBxf7pdhJQPm"
  token_obtained_at = 2023-05-18T02:43:29Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "ae012bdb3d0d"
  url = "http://gitlab"
  id = 1
  token = "xBSRKr9GzdBNydByMM5U"
  token_obtained_at = 2023-05-18T03:31:38Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "d0fb6d9d5584"
  url = "http://gitlab"
  id = 1
  token = "Lydyf-T4rBh8Xxp5_t4s"
  token_obtained_at = 2023-05-18T14:15:09Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "0ab144a339c1"
  url = "http://gitlab"
  id = 1
  token = "zmZUwLJ7VxPNzamzBdBX"
  token_obtained_at = 2023-05-18T18:09:46Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "696cd1880c63"
  url = "http://gitlab"
  id = 1
  token = "Bd7y8TUtpsgXRkTJiD4J"
  token_obtained_at = 2023-05-18T19:42:26Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
