concurrent = 4
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "58ac1f5ba888"
  url = "http://gitlab"
  id = 1
  token = "xPtN-42x-ZXrV_wvghVT"
  token_obtained_at = 2023-01-12T00:30:22Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "0b1c7dc29d95"
  url = "http://gitlab"
  id = 1
  token = "ixBzso-WXjXxgcX3-aZ4"
  token_obtained_at = 2023-01-12T00:49:54Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "0b1c7dc29d95"
  url = "http://gitlab"
  id = 2
  token = "6rornvg7xXjc4y4ZMxs5"
  token_obtained_at = 2023-01-12T00:50:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "0b1c7dc29d95"
  url = "http://gitlab"
  id = 3
  token = "TFr1gP8X7us5_9ZEFmeN"
  token_obtained_at = 2023-01-12T00:50:51Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "0b1c7dc29d95"
  url = "http://gitlab"
  id = 4
  token = "6UzL-FSv8sExX1RtTsh7"
  token_obtained_at = 2023-01-12T00:51:54Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "0b1c7dc29d95"
  url = "http://gitlab"
  id = 5
  token = "kAD1VPg_zHyyw-xcZFGP"
  token_obtained_at = 2023-01-12T00:52:19Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "0b1c7dc29d95"
  url = "http://gitlab"
  id = 36
  token = "pvv-xcMCANM1znScigva"
  token_obtained_at = 2023-01-12T22:57:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
