appearance:
  title: "ForAllSecure demo Gitlab"
  #logo: "https://storage.googleapis.com/forallsecure-website.appspot.com/fas-logo-block.svg"

settings:
  # elasticsearch:
  #   url: http://elasticsearch.mygitlab.com
  #   username: !env ELASTICSEARCH_USERNAME
  #   password: !env ELASTICSEARCH_PASSWORD
  recaptcha_enabled: no
  #terms: !include toc.md
  # plantuml:
  #   enabled: true
  #   url: 'http://plantuml.url'

features:
  # - name: sourcegraph
  #   value: true
  #   groups:
  #     - mygroup1
  #   projects:
  #     - mygroup2/myproject
  #   users:
  #     - myuser

instance_variables:
  MAPI_TOKEN:
    value: !env MAPI_TOKEN
    masked: true
    protected: false
  MAYHEM_TOKEN:
    value: !env MAYHEM_TOKEN
    masked: true
    protected: false
  MAYHEM_URL:
    value: !env MAYHEM_URL
    masked: true
    protected: false